// Package spike1_real tests with the ACTUAL google/fhir Patient proto.
// This is the definitive spike — uses real compiled types, not mocks.
package spike1_real

import (
	"encoding/json"
	"testing"

	"google.golang.org/protobuf/encoding/protojson"

	codepb "github.com/google/fhir/go/proto/google/fhir/proto/r4/core/codes_go_proto"
	dtpb "github.com/google/fhir/go/proto/google/fhir/proto/r4/core/datatypes_go_proto"
	pb "github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/patient_go_proto"
)

func TestRealGoogleFHIRPatientMarshal(t *testing.T) {
	// Build a Patient using the REAL google/fhir proto types
	patient := &pb.Patient{
		Id:     &dtpb.Id{Value: "synthea-abc123"},
		Active: &dtpb.Boolean{Value: true},
		Name: []*dtpb.HumanName{
			{
				Family: &dtpb.String{Value: "Smith"},
				Given: []*dtpb.String{
					{Value: "John"},
					{Value: "Michael"},
				},
			},
		},
		Gender: &pb.Patient_GenderCode{
			Value: codepb.AdministrativeGenderCode_MALE,
		},
		BirthDate: &dtpb.Date{
			ValueUs:   631152000000000, // 1990-01-01 in microseconds
			Precision: dtpb.Date_DAY,
		},
	}

	// Marshal with protojson — this is what proto2type would produce
	marshaler := protojson.MarshalOptions{
		Indent:        "  ",
		UseProtoNames: true,
	}
	protoBytes, err := marshaler.Marshal(patient)
	if err != nil {
		t.Fatalf("protojson.Marshal failed: %v", err)
	}

	t.Logf("=== REAL google/fhir protojson.Marshal() output ===\n%s", string(protoBytes))

	// Parse and inspect the structure
	var parsed map[string]interface{}
	if err := json.Unmarshal(protoBytes, &parsed); err != nil {
		t.Fatalf("json.Unmarshal failed: %v", err)
	}

	// Check: is "id" wrapped?
	idVal := parsed["id"]
	switch v := idVal.(type) {
	case string:
		t.Logf("id is flat string: %q ✅ (valid FHIR)", v)
	case map[string]interface{}:
		t.Logf("id is WRAPPED: %v ❌ (invalid FHIR — needs unwrapping)", v)
	default:
		t.Logf("id is type %T: %v", idVal, idVal)
	}

	// Check: is "name[0].family" wrapped?
	if names, ok := parsed["name"].([]interface{}); ok && len(names) > 0 {
		name0 := names[0].(map[string]interface{})
		familyVal := name0["family"]
		switch v := familyVal.(type) {
		case string:
			t.Logf("name[0].family is flat string: %q ✅ (valid FHIR)", v)
		case map[string]interface{}:
			t.Logf("name[0].family is WRAPPED: %v ❌ (invalid FHIR — needs unwrapping)", v)
		default:
			t.Logf("name[0].family is type %T: %v", familyVal, familyVal)
		}

		// Check given
		if given, ok := name0["given"].([]interface{}); ok && len(given) > 0 {
			switch v := given[0].(type) {
			case string:
				t.Logf("name[0].given[0] is flat string: %q ✅", v)
			case map[string]interface{}:
				t.Logf("name[0].given[0] is WRAPPED: %v ❌", v)
			default:
				t.Logf("name[0].given[0] is type %T: %v", given[0], given[0])
			}
		}
	}

	// Check: gender
	if gender, ok := parsed["gender"]; ok {
		t.Logf("gender: %v (type %T)", gender, gender)
	}

	t.Log("\n=== SPIKE 1 CONCLUSION ===")
	t.Log("If you see ❌ marks above, protojson.Marshal() produces INVALID FHIR JSON.")
	t.Log("The ToFHIRJSON() converter must unwrap primitives to produce valid output.")
	t.Log("This transformation is MECHANICAL and can be generated by proto2type.")
}
