// Package activity defines the Temporal activities for FHIR Bundle ingestion.
package activity

import (
	"context"
	"fmt"
	"log/slog"

	"github.com/flint-fhir/flint/automq"
	"github.com/flint-fhir/flint/store/postgres"
)

// --- Activity Inputs ---

// WriteMedplumBatchInput is the input for the WriteMedplumBatch activity.
type WriteMedplumBatchInput struct {
	TenantID       string
	ResourceProtos [][]byte
	ResourceTypes  []string
	ResourceIDs    []string
}

// WritePostgresBatchInput is the input for the WritePostgresBatch activity.
type WritePostgresBatchInput struct {
	TenantID       string
	BundleID       string
	ResourceProtos [][]byte
	ResourceTypes  []string
	ResourceIDs    []string
}

// PublishToAutoMQInput is the input for the PublishToAutoMQ activity.
type PublishToAutoMQInput struct {
	TenantID       string
	ResourceProtos [][]byte
	ResourceTypes  []string
	ResourceIDs    []string
	Op             string // "U" for upsert, "D" for delete
}

// --- Activities ---

// Activities holds dependencies for all ingest activities.
type Activities struct {
	Store    *postgres.Store
	Producer *automq.Producer // nil = skip AutoMQ publish
	Logger   *slog.Logger
	// IndexExtractors maps resource type → extraction function
	// These are generated by proto2type (postgres_mode=search_index)
	IndexExtractors map[string]IndexExtractorFunc
}

// IndexExtractorFunc extracts search indexes from a proto-encoded resource.
type IndexExtractorFunc = postgres.IndexExtractorFunc

// WriteMedplumBatch forwards FHIR resources to Medplum.
// This is temporary — Medplum will be replaced by Flint's own FHIR server in H3.
func (a *Activities) WriteMedplumBatch(ctx context.Context, input WriteMedplumBatchInput) error {
	// TODO: implement Medplum API client
	// For now, log and skip — Medplum integration will be added in Phase 1.5
	a.Logger.Info("WriteMedplumBatch (stub)",
		"tenant", input.TenantID,
		"resources", len(input.ResourceProtos),
	)
	return nil
}

// WritePostgresBatch writes resources to Postgres in a single transaction.
// This is the hot path — upsert resource blob + delete old indexes + bulk insert new indexes.
func (a *Activities) WritePostgresBatch(ctx context.Context, input WritePostgresBatchInput) error {
	inputs := make([]postgres.ResourceInput, len(input.ResourceProtos))

	for i := range input.ResourceProtos {
		resType := input.ResourceTypes[i]
		resID := input.ResourceIDs[i]

		ri := postgres.ResourceInput{
			TenantID:       input.TenantID,
			ResType:        resType,
			ResID:          resID,
			ResourceProto:  input.ResourceProtos[i],
			IdempotencyKey: input.BundleID,
		}

		// Extract search indexes if we have an extractor for this resource type
		if extractor, ok := a.IndexExtractors[resType]; ok {
			idx, err := extractor(input.TenantID, resID, input.ResourceProtos[i])
			if err != nil {
				a.Logger.Warn("index extraction failed, storing without indexes",
					"type", resType, "id", resID, "error", err)
			} else {
				ri.SearchIndexes = idx
			}
		}

		inputs[i] = ri
	}

	if err := a.Store.WriteBatch(ctx, inputs); err != nil {
		return fmt.Errorf("postgres batch write: %w", err)
	}

	a.Logger.Info("WritePostgresBatch complete",
		"tenant", input.TenantID,
		"resources", len(inputs),
		"bundle", input.BundleID,
	)
	return nil
}

// PublishToAutoMQ publishes per-resource-type proto messages to AutoMQ topics.
// Each resource type maps to a topic: {TopicPrefix}{ResourceType} (e.g., "fhir.Patient").
// Messages are keyed by resource ID for partition locality and log compaction.
func (a *Activities) PublishToAutoMQ(ctx context.Context, input PublishToAutoMQInput) error {
	if a.Producer == nil {
		a.Logger.Info("PublishToAutoMQ skipped (no producer configured)",
			"tenant", input.TenantID,
			"resources", len(input.ResourceProtos),
		)
		return nil
	}

	messages := make([]automq.Message, len(input.ResourceProtos))
	for i := range input.ResourceProtos {
		messages[i] = automq.Message{
			TenantID:  input.TenantID,
			ResType:   input.ResourceTypes[i],
			ResID:     input.ResourceIDs[i],
			ProtoData: input.ResourceProtos[i],
			Op:        input.Op,
		}
	}

	if err := a.Producer.Publish(ctx, messages); err != nil {
		return fmt.Errorf("automq publish: %w", err)
	}

	a.Logger.Info("PublishToAutoMQ complete",
		"tenant", input.TenantID,
		"resources", len(messages),
		"op", input.Op,
	)
	return nil
}
