// Minimal proto that mimics google/fhir's primitive wrapping pattern.
// Used for Spike 1 to validate protojson.Marshal() output format
// without needing the full google/fhir module.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: spike/spike1_proto/mini_fhir.proto

package spike1_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenderCode int32

const (
	GenderCode_GENDER_CODE_UNSPECIFIED GenderCode = 0
	GenderCode_MALE                    GenderCode = 1
	GenderCode_FEMALE                  GenderCode = 2
	GenderCode_OTHER                   GenderCode = 3
	GenderCode_UNKNOWN                 GenderCode = 4
)

// Enum value maps for GenderCode.
var (
	GenderCode_name = map[int32]string{
		0: "GENDER_CODE_UNSPECIFIED",
		1: "MALE",
		2: "FEMALE",
		3: "OTHER",
		4: "UNKNOWN",
	}
	GenderCode_value = map[string]int32{
		"GENDER_CODE_UNSPECIFIED": 0,
		"MALE":                    1,
		"FEMALE":                  2,
		"OTHER":                   3,
		"UNKNOWN":                 4,
	}
)

func (x GenderCode) Enum() *GenderCode {
	p := new(GenderCode)
	*p = x
	return p
}

func (x GenderCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenderCode) Descriptor() protoreflect.EnumDescriptor {
	return file_spike_spike1_proto_mini_fhir_proto_enumTypes[0].Descriptor()
}

func (GenderCode) Type() protoreflect.EnumType {
	return &file_spike_spike1_proto_mini_fhir_proto_enumTypes[0]
}

func (x GenderCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenderCode.Descriptor instead.
func (GenderCode) EnumDescriptor() ([]byte, []int) {
	return file_spike_spike1_proto_mini_fhir_proto_rawDescGZIP(), []int{0}
}

// Mimics google/fhir String wrapper
type FHIRString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Extension     []*Extension           `protobuf:"bytes,3,rep,name=extension,proto3" json:"extension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FHIRString) Reset() {
	*x = FHIRString{}
	mi := &file_spike_spike1_proto_mini_fhir_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FHIRString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FHIRString) ProtoMessage() {}

func (x *FHIRString) ProtoReflect() protoreflect.Message {
	mi := &file_spike_spike1_proto_mini_fhir_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FHIRString.ProtoReflect.Descriptor instead.
func (*FHIRString) Descriptor() ([]byte, []int) {
	return file_spike_spike1_proto_mini_fhir_proto_rawDescGZIP(), []int{0}
}

func (x *FHIRString) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *FHIRString) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FHIRString) GetExtension() []*Extension {
	if x != nil {
		return x.Extension
	}
	return nil
}

// Mimics google/fhir Boolean wrapper
type FHIRBoolean struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Extension     []*Extension           `protobuf:"bytes,3,rep,name=extension,proto3" json:"extension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FHIRBoolean) Reset() {
	*x = FHIRBoolean{}
	mi := &file_spike_spike1_proto_mini_fhir_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FHIRBoolean) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FHIRBoolean) ProtoMessage() {}

func (x *FHIRBoolean) ProtoReflect() protoreflect.Message {
	mi := &file_spike_spike1_proto_mini_fhir_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FHIRBoolean.ProtoReflect.Descriptor instead.
func (*FHIRBoolean) Descriptor() ([]byte, []int) {
	return file_spike_spike1_proto_mini_fhir_proto_rawDescGZIP(), []int{1}
}

func (x *FHIRBoolean) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

func (x *FHIRBoolean) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FHIRBoolean) GetExtension() []*Extension {
	if x != nil {
		return x.Extension
	}
	return nil
}

// Mimics google/fhir Date wrapper
type FHIRDate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Extension     []*Extension           `protobuf:"bytes,3,rep,name=extension,proto3" json:"extension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FHIRDate) Reset() {
	*x = FHIRDate{}
	mi := &file_spike_spike1_proto_mini_fhir_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FHIRDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FHIRDate) ProtoMessage() {}

func (x *FHIRDate) ProtoReflect() protoreflect.Message {
	mi := &file_spike_spike1_proto_mini_fhir_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FHIRDate.ProtoReflect.Descriptor instead.
func (*FHIRDate) Descriptor() ([]byte, []int) {
	return file_spike_spike1_proto_mini_fhir_proto_rawDescGZIP(), []int{2}
}

func (x *FHIRDate) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *FHIRDate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FHIRDate) GetExtension() []*Extension {
	if x != nil {
		return x.Extension
	}
	return nil
}

// Mimics Extension
type Extension struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Url   string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Extension_ValueString
	//	*Extension_ValueBoolean
	//	*Extension_ValueDate
	//	*Extension_ValueDateTime
	Value         isExtension_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Extension) Reset() {
	*x = Extension{}
	mi := &file_spike_spike1_proto_mini_fhir_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Extension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extension) ProtoMessage() {}

func (x *Extension) ProtoReflect() protoreflect.Message {
	mi := &file_spike_spike1_proto_mini_fhir_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extension.ProtoReflect.Descriptor instead.
func (*Extension) Descriptor() ([]byte, []int) {
	return file_spike_spike1_proto_mini_fhir_proto_rawDescGZIP(), []int{3}
}

func (x *Extension) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Extension) GetValue() isExtension_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Extension) GetValueString() *FHIRString {
	if x != nil {
		if x, ok := x.Value.(*Extension_ValueString); ok {
			return x.ValueString
		}
	}
	return nil
}

func (x *Extension) GetValueBoolean() *FHIRBoolean {
	if x != nil {
		if x, ok := x.Value.(*Extension_ValueBoolean); ok {
			return x.ValueBoolean
		}
	}
	return nil
}

func (x *Extension) GetValueDate() *FHIRDate {
	if x != nil {
		if x, ok := x.Value.(*Extension_ValueDate); ok {
			return x.ValueDate
		}
	}
	return nil
}

func (x *Extension) GetValueDateTime() string {
	if x != nil {
		if x, ok := x.Value.(*Extension_ValueDateTime); ok {
			return x.ValueDateTime
		}
	}
	return ""
}

type isExtension_Value interface {
	isExtension_Value()
}

type Extension_ValueString struct {
	ValueString *FHIRString `protobuf:"bytes,2,opt,name=value_string,json=valueString,proto3,oneof"`
}

type Extension_ValueBoolean struct {
	ValueBoolean *FHIRBoolean `protobuf:"bytes,3,opt,name=value_boolean,json=valueBoolean,proto3,oneof"`
}

type Extension_ValueDate struct {
	ValueDate *FHIRDate `protobuf:"bytes,4,opt,name=value_date,json=valueDate,proto3,oneof"`
}

type Extension_ValueDateTime struct {
	ValueDateTime string `protobuf:"bytes,5,opt,name=value_date_time,json=valueDateTime,proto3,oneof"`
}

func (*Extension_ValueString) isExtension_Value() {}

func (*Extension_ValueBoolean) isExtension_Value() {}

func (*Extension_ValueDate) isExtension_Value() {}

func (*Extension_ValueDateTime) isExtension_Value() {}

// Mimics google/fhir Coding
type Coding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	System        *FHIRString            `protobuf:"bytes,1,opt,name=system,proto3" json:"system,omitempty"`
	Code          *FHIRString            `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Display       *FHIRString            `protobuf:"bytes,3,opt,name=display,proto3" json:"display,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coding) Reset() {
	*x = Coding{}
	mi := &file_spike_spike1_proto_mini_fhir_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coding) ProtoMessage() {}

func (x *Coding) ProtoReflect() protoreflect.Message {
	mi := &file_spike_spike1_proto_mini_fhir_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coding.ProtoReflect.Descriptor instead.
func (*Coding) Descriptor() ([]byte, []int) {
	return file_spike_spike1_proto_mini_fhir_proto_rawDescGZIP(), []int{4}
}

func (x *Coding) GetSystem() *FHIRString {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *Coding) GetCode() *FHIRString {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *Coding) GetDisplay() *FHIRString {
	if x != nil {
		return x.Display
	}
	return nil
}

// Mimics google/fhir Identifier
type Identifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	System        *FHIRString            `protobuf:"bytes,1,opt,name=system,proto3" json:"system,omitempty"`
	Value         *FHIRString            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identifier) Reset() {
	*x = Identifier{}
	mi := &file_spike_spike1_proto_mini_fhir_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier) ProtoMessage() {}

func (x *Identifier) ProtoReflect() protoreflect.Message {
	mi := &file_spike_spike1_proto_mini_fhir_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier.ProtoReflect.Descriptor instead.
func (*Identifier) Descriptor() ([]byte, []int) {
	return file_spike_spike1_proto_mini_fhir_proto_rawDescGZIP(), []int{5}
}

func (x *Identifier) GetSystem() *FHIRString {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *Identifier) GetValue() *FHIRString {
	if x != nil {
		return x.Value
	}
	return nil
}

// Mimics google/fhir HumanName
type HumanName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Family        *FHIRString            `protobuf:"bytes,1,opt,name=family,proto3" json:"family,omitempty"`
	Given         []*FHIRString          `protobuf:"bytes,2,rep,name=given,proto3" json:"given,omitempty"`
	Prefix        []*FHIRString          `protobuf:"bytes,3,rep,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HumanName) Reset() {
	*x = HumanName{}
	mi := &file_spike_spike1_proto_mini_fhir_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HumanName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanName) ProtoMessage() {}

func (x *HumanName) ProtoReflect() protoreflect.Message {
	mi := &file_spike_spike1_proto_mini_fhir_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanName.ProtoReflect.Descriptor instead.
func (*HumanName) Descriptor() ([]byte, []int) {
	return file_spike_spike1_proto_mini_fhir_proto_rawDescGZIP(), []int{6}
}

func (x *HumanName) GetFamily() *FHIRString {
	if x != nil {
		return x.Family
	}
	return nil
}

func (x *HumanName) GetGiven() []*FHIRString {
	if x != nil {
		return x.Given
	}
	return nil
}

func (x *HumanName) GetPrefix() []*FHIRString {
	if x != nil {
		return x.Prefix
	}
	return nil
}

// Mimics google/fhir Patient (Big 5 fields only)
type MiniPatient struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   *FHIRString            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Identifier           []*Identifier          `protobuf:"bytes,2,rep,name=identifier,proto3" json:"identifier,omitempty"`
	Active               *FHIRBoolean           `protobuf:"bytes,3,opt,name=active,proto3" json:"active,omitempty"`
	Name                 []*HumanName           `protobuf:"bytes,4,rep,name=name,proto3" json:"name,omitempty"`
	Gender               GenderCode             `protobuf:"varint,5,opt,name=gender,proto3,enum=flint.spike.GenderCode" json:"gender,omitempty"`
	BirthDate            *FHIRDate              `protobuf:"bytes,6,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	DeceasedBoolean      *FHIRBoolean           `protobuf:"bytes,7,opt,name=deceased_boolean,json=deceasedBoolean,proto3" json:"deceased_boolean,omitempty"`
	MultipleBirthBoolean *FHIRBoolean           `protobuf:"bytes,8,opt,name=multiple_birth_boolean,json=multipleBirthBoolean,proto3" json:"multiple_birth_boolean,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MiniPatient) Reset() {
	*x = MiniPatient{}
	mi := &file_spike_spike1_proto_mini_fhir_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiniPatient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiniPatient) ProtoMessage() {}

func (x *MiniPatient) ProtoReflect() protoreflect.Message {
	mi := &file_spike_spike1_proto_mini_fhir_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiniPatient.ProtoReflect.Descriptor instead.
func (*MiniPatient) Descriptor() ([]byte, []int) {
	return file_spike_spike1_proto_mini_fhir_proto_rawDescGZIP(), []int{7}
}

func (x *MiniPatient) GetId() *FHIRString {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *MiniPatient) GetIdentifier() []*Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *MiniPatient) GetActive() *FHIRBoolean {
	if x != nil {
		return x.Active
	}
	return nil
}

func (x *MiniPatient) GetName() []*HumanName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *MiniPatient) GetGender() GenderCode {
	if x != nil {
		return x.Gender
	}
	return GenderCode_GENDER_CODE_UNSPECIFIED
}

func (x *MiniPatient) GetBirthDate() *FHIRDate {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *MiniPatient) GetDeceasedBoolean() *FHIRBoolean {
	if x != nil {
		return x.DeceasedBoolean
	}
	return nil
}

func (x *MiniPatient) GetMultipleBirthBoolean() *FHIRBoolean {
	if x != nil {
		return x.MultipleBirthBoolean
	}
	return nil
}

var File_spike_spike1_proto_mini_fhir_proto protoreflect.FileDescriptor

const file_spike_spike1_proto_mini_fhir_proto_rawDesc = "" +
	"\n" +
	"\"spike/spike1_proto/mini_fhir.proto\x12\vflint.spike\"h\n" +
	"\n" +
	"FHIRString\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x124\n" +
	"\textension\x18\x03 \x03(\v2\x16.flint.spike.ExtensionR\textension\"i\n" +
	"\vFHIRBoolean\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x124\n" +
	"\textension\x18\x03 \x03(\v2\x16.flint.spike.ExtensionR\textension\"f\n" +
	"\bFHIRDate\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x124\n" +
	"\textension\x18\x03 \x03(\v2\x16.flint.spike.ExtensionR\textension\"\x87\x02\n" +
	"\tExtension\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12<\n" +
	"\fvalue_string\x18\x02 \x01(\v2\x17.flint.spike.FHIRStringH\x00R\vvalueString\x12?\n" +
	"\rvalue_boolean\x18\x03 \x01(\v2\x18.flint.spike.FHIRBooleanH\x00R\fvalueBoolean\x126\n" +
	"\n" +
	"value_date\x18\x04 \x01(\v2\x15.flint.spike.FHIRDateH\x00R\tvalueDate\x12(\n" +
	"\x0fvalue_date_time\x18\x05 \x01(\tH\x00R\rvalueDateTimeB\a\n" +
	"\x05value\"\x99\x01\n" +
	"\x06Coding\x12/\n" +
	"\x06system\x18\x01 \x01(\v2\x17.flint.spike.FHIRStringR\x06system\x12+\n" +
	"\x04code\x18\x02 \x01(\v2\x17.flint.spike.FHIRStringR\x04code\x121\n" +
	"\adisplay\x18\x03 \x01(\v2\x17.flint.spike.FHIRStringR\adisplay\"l\n" +
	"\n" +
	"Identifier\x12/\n" +
	"\x06system\x18\x01 \x01(\v2\x17.flint.spike.FHIRStringR\x06system\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.flint.spike.FHIRStringR\x05value\"\x9c\x01\n" +
	"\tHumanName\x12/\n" +
	"\x06family\x18\x01 \x01(\v2\x17.flint.spike.FHIRStringR\x06family\x12-\n" +
	"\x05given\x18\x02 \x03(\v2\x17.flint.spike.FHIRStringR\x05given\x12/\n" +
	"\x06prefix\x18\x03 \x03(\v2\x17.flint.spike.FHIRStringR\x06prefix\"\xc9\x03\n" +
	"\vMiniPatient\x12'\n" +
	"\x02id\x18\x01 \x01(\v2\x17.flint.spike.FHIRStringR\x02id\x127\n" +
	"\n" +
	"identifier\x18\x02 \x03(\v2\x17.flint.spike.IdentifierR\n" +
	"identifier\x120\n" +
	"\x06active\x18\x03 \x01(\v2\x18.flint.spike.FHIRBooleanR\x06active\x12*\n" +
	"\x04name\x18\x04 \x03(\v2\x16.flint.spike.HumanNameR\x04name\x12/\n" +
	"\x06gender\x18\x05 \x01(\x0e2\x17.flint.spike.GenderCodeR\x06gender\x124\n" +
	"\n" +
	"birth_date\x18\x06 \x01(\v2\x15.flint.spike.FHIRDateR\tbirthDate\x12C\n" +
	"\x10deceased_boolean\x18\a \x01(\v2\x18.flint.spike.FHIRBooleanR\x0fdeceasedBoolean\x12N\n" +
	"\x16multiple_birth_boolean\x18\b \x01(\v2\x18.flint.spike.FHIRBooleanR\x14multipleBirthBoolean*W\n" +
	"\n" +
	"GenderCode\x12\x1b\n" +
	"\x17GENDER_CODE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04MALE\x10\x01\x12\n" +
	"\n" +
	"\x06FEMALE\x10\x02\x12\t\n" +
	"\x05OTHER\x10\x03\x12\v\n" +
	"\aUNKNOWN\x10\x04B0Z.github.com/flint-fhir/flint/spike/spike1_protob\x06proto3"

var (
	file_spike_spike1_proto_mini_fhir_proto_rawDescOnce sync.Once
	file_spike_spike1_proto_mini_fhir_proto_rawDescData []byte
)

func file_spike_spike1_proto_mini_fhir_proto_rawDescGZIP() []byte {
	file_spike_spike1_proto_mini_fhir_proto_rawDescOnce.Do(func() {
		file_spike_spike1_proto_mini_fhir_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spike_spike1_proto_mini_fhir_proto_rawDesc), len(file_spike_spike1_proto_mini_fhir_proto_rawDesc)))
	})
	return file_spike_spike1_proto_mini_fhir_proto_rawDescData
}

var file_spike_spike1_proto_mini_fhir_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_spike_spike1_proto_mini_fhir_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_spike_spike1_proto_mini_fhir_proto_goTypes = []any{
	(GenderCode)(0),     // 0: flint.spike.GenderCode
	(*FHIRString)(nil),  // 1: flint.spike.FHIRString
	(*FHIRBoolean)(nil), // 2: flint.spike.FHIRBoolean
	(*FHIRDate)(nil),    // 3: flint.spike.FHIRDate
	(*Extension)(nil),   // 4: flint.spike.Extension
	(*Coding)(nil),      // 5: flint.spike.Coding
	(*Identifier)(nil),  // 6: flint.spike.Identifier
	(*HumanName)(nil),   // 7: flint.spike.HumanName
	(*MiniPatient)(nil), // 8: flint.spike.MiniPatient
}
var file_spike_spike1_proto_mini_fhir_proto_depIdxs = []int32{
	4,  // 0: flint.spike.FHIRString.extension:type_name -> flint.spike.Extension
	4,  // 1: flint.spike.FHIRBoolean.extension:type_name -> flint.spike.Extension
	4,  // 2: flint.spike.FHIRDate.extension:type_name -> flint.spike.Extension
	1,  // 3: flint.spike.Extension.value_string:type_name -> flint.spike.FHIRString
	2,  // 4: flint.spike.Extension.value_boolean:type_name -> flint.spike.FHIRBoolean
	3,  // 5: flint.spike.Extension.value_date:type_name -> flint.spike.FHIRDate
	1,  // 6: flint.spike.Coding.system:type_name -> flint.spike.FHIRString
	1,  // 7: flint.spike.Coding.code:type_name -> flint.spike.FHIRString
	1,  // 8: flint.spike.Coding.display:type_name -> flint.spike.FHIRString
	1,  // 9: flint.spike.Identifier.system:type_name -> flint.spike.FHIRString
	1,  // 10: flint.spike.Identifier.value:type_name -> flint.spike.FHIRString
	1,  // 11: flint.spike.HumanName.family:type_name -> flint.spike.FHIRString
	1,  // 12: flint.spike.HumanName.given:type_name -> flint.spike.FHIRString
	1,  // 13: flint.spike.HumanName.prefix:type_name -> flint.spike.FHIRString
	1,  // 14: flint.spike.MiniPatient.id:type_name -> flint.spike.FHIRString
	6,  // 15: flint.spike.MiniPatient.identifier:type_name -> flint.spike.Identifier
	2,  // 16: flint.spike.MiniPatient.active:type_name -> flint.spike.FHIRBoolean
	7,  // 17: flint.spike.MiniPatient.name:type_name -> flint.spike.HumanName
	0,  // 18: flint.spike.MiniPatient.gender:type_name -> flint.spike.GenderCode
	3,  // 19: flint.spike.MiniPatient.birth_date:type_name -> flint.spike.FHIRDate
	2,  // 20: flint.spike.MiniPatient.deceased_boolean:type_name -> flint.spike.FHIRBoolean
	2,  // 21: flint.spike.MiniPatient.multiple_birth_boolean:type_name -> flint.spike.FHIRBoolean
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_spike_spike1_proto_mini_fhir_proto_init() }
func file_spike_spike1_proto_mini_fhir_proto_init() {
	if File_spike_spike1_proto_mini_fhir_proto != nil {
		return
	}
	file_spike_spike1_proto_mini_fhir_proto_msgTypes[3].OneofWrappers = []any{
		(*Extension_ValueString)(nil),
		(*Extension_ValueBoolean)(nil),
		(*Extension_ValueDate)(nil),
		(*Extension_ValueDateTime)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spike_spike1_proto_mini_fhir_proto_rawDesc), len(file_spike_spike1_proto_mini_fhir_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spike_spike1_proto_mini_fhir_proto_goTypes,
		DependencyIndexes: file_spike_spike1_proto_mini_fhir_proto_depIdxs,
		EnumInfos:         file_spike_spike1_proto_mini_fhir_proto_enumTypes,
		MessageInfos:      file_spike_spike1_proto_mini_fhir_proto_msgTypes,
	}.Build()
	File_spike_spike1_proto_mini_fhir_proto = out.File
	file_spike_spike1_proto_mini_fhir_proto_goTypes = nil
	file_spike_spike1_proto_mini_fhir_proto_depIdxs = nil
}
