// Package postgres implements the Flint FHIR resource store using PostgreSQL.
//
// It stores FHIR resources as proto-encoded blobs with HAPI-style search index
// tables (spidx_*) for efficient FHIR search operations. Resources are written
// in a single transaction: upsert blob + delete old indexes + bulk insert new indexes.
package postgres

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"

	genpostgres "github.com/flint-fhir/flint/gen/go/store/postgres"
)

var (
	// ErrVersionConflict is returned when an optimistic concurrency check (If-Match / ExpectedVersion) fails.
	ErrVersionConflict = errors.New("version conflict")
	// ErrResourceDeleted is returned when reading a resource or version that has been soft-deleted.
	ErrResourceDeleted = errors.New("resource deleted")
	// ErrInvalidETag is returned when an ETag / If-Match header cannot be parsed as a positive version integer.
	ErrInvalidETag = errors.New("invalid ETag")
)

// SearchIndexes holds all extracted search index rows for a resource.
// This type is generated by proto2type (postgres_mode=search_index).
type SearchIndexes = genpostgres.SearchIndexes

type SpidxString = genpostgres.SpidxString
type SpidxToken = genpostgres.SpidxToken
type SpidxDate = genpostgres.SpidxDate
type SpidxReference = genpostgres.SpidxReference
type SpidxQuantity = genpostgres.SpidxQuantity
type SpidxURI = genpostgres.SpidxURI

// IndexExtractorFunc extracts search indexes from a proto-encoded resource.
type IndexExtractorFunc func(tenantID string, resID string, protoBytes []byte) (*SearchIndexes, error)

// ResourceInput is the input to write a single FHIR resource.
type ResourceInput struct {
	TenantID        string
	ResType         string
	ResID           string
	ResourceProto   []byte         // proto-encoded FHIR resource
	SearchIndexes   *SearchIndexes // extracted search index rows
	IdempotencyKey  string         // Bundle ID for dedup
	ExpectedVersion int            // Optional: if > 0, enforces optimistic concurrency (If-Match)
}

// ResourceRecord represents a stored FHIR resource version and its metadata.
type ResourceRecord struct {
	TenantID      string
	ResType       string
	ResID         string
	ResVersion    int
	LastUpdated   time.Time
	ResourceProto []byte
	IsDeleted     bool
	Created       bool // True if this write created a new resource or resurrected a deleted one
}

// FormatETag formats a positive integer resource version as a weak HTTP ETag per FHIR R4 (e.g., W/"1").
func FormatETag(version int) string {
	return fmt.Sprintf(`W/"%d"`, version)
}

// ParseETagVersion parses an HTTP ETag or If-Match header (e.g., W/"3", "3", or 3) into a positive version integer.
func ParseETagVersion(etag string) (int, error) {
	s := strings.TrimSpace(etag)
	if s == "" {
		return 0, fmt.Errorf("%w: empty value", ErrInvalidETag)
	}
	if strings.HasPrefix(s, "W/") || strings.HasPrefix(s, "w/") {
		s = strings.TrimSpace(s[2:])
		if len(s) < 2 || !strings.HasPrefix(s, `"`) || !strings.HasSuffix(s, `"`) {
			return 0, fmt.Errorf("%w: %q", ErrInvalidETag, etag)
		}
		s = s[1 : len(s)-1]
	} else if strings.HasPrefix(s, `"`) || strings.HasSuffix(s, `"`) {
		if len(s) < 2 || !strings.HasPrefix(s, `"`) || !strings.HasSuffix(s, `"`) {
			return 0, fmt.Errorf("%w: %q", ErrInvalidETag, etag)
		}
		s = s[1 : len(s)-1]
	}
	v, err := strconv.Atoi(s)
	if err != nil || v <= 0 {
		return 0, fmt.Errorf("%w: %q", ErrInvalidETag, etag)
	}
	return v, nil
}

// Store provides FHIR resource storage operations on Postgres.
type Store struct {
	db *sql.DB
}

// New creates a new Postgres FHIR resource store.
func New(db *sql.DB) *Store {
	return &Store{db: db}
}

// WriteResource writes a single resource in a single transaction:
// 1. Upsert the resource blob (and append to fhir_resource_history)
// 2. Delete old search indexes for this resource
// 3. Bulk insert new search indexes
//
// This is idempotent: re-processing the same resource produces the same state.
func (s *Store) WriteResource(ctx context.Context, input ResourceInput) error {
	_, err := s.WriteResourceWithMeta(ctx, input)
	return err
}

// WriteResourceWithMeta writes a single resource in a transaction, enforcing
// ExpectedVersion if > 0, recording a snapshot in fhir_resource_history, and
// returning the resulting version metadata.
func (s *Store) WriteResourceWithMeta(ctx context.Context, input ResourceInput) (*ResourceRecord, error) {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return nil, fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback() //nolint:errcheck

	rec, err := writeResourceInTx(ctx, tx, input)
	if err != nil {
		return nil, err
	}

	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return rec, nil
}

// WriteBatch writes multiple resources in a single transaction.
// This is the hot path for FHIR Bundle ingestion (R8: batch per Bundle).
func (s *Store) WriteBatch(ctx context.Context, inputs []ResourceInput) error {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback() //nolint:errcheck

	for _, input := range inputs {
		if _, err := writeResourceInTx(ctx, tx, input); err != nil {
			return fmt.Errorf("resource %s/%s: %w", input.ResType, input.ResID, err)
		}
	}

	return tx.Commit()
}

func writeResourceInTx(ctx context.Context, tx *sql.Tx, input ResourceInput) (*ResourceRecord, error) {
	var curVersion int
	var curDeleted bool
	err := tx.QueryRowContext(ctx, `
		SELECT res_version, is_deleted FROM fhir_resource
		WHERE tenant_id = $1 AND res_type = $2 AND res_id = $3
		FOR UPDATE
	`, input.TenantID, input.ResType, input.ResID).Scan(&curVersion, &curDeleted)

	created := false
	if errors.Is(err, sql.ErrNoRows) {
		created = true
		if input.ExpectedVersion > 0 {
			return nil, fmt.Errorf("%w: resource does not exist (expected version %d)", ErrVersionConflict, input.ExpectedVersion)
		}
	} else if err != nil {
		return nil, fmt.Errorf("check current version: %w", err)
	} else {
		if curDeleted {
			created = true
		}
		if input.ExpectedVersion > 0 && (curDeleted || curVersion != input.ExpectedVersion) {
			return nil, fmt.Errorf("%w: expected version %d, current version %d", ErrVersionConflict, input.ExpectedVersion, curVersion)
		}
	}

	// 1. Upsert resource blob
	var newVersion int
	var lastUpdated time.Time
	err = tx.QueryRowContext(ctx, `
		INSERT INTO fhir_resource (tenant_id, res_type, res_id, resource_proto, idempotency_key, last_updated)
		VALUES ($1, $2, $3, $4, $5, NOW())
		ON CONFLICT (tenant_id, res_type, res_id) DO UPDATE SET
			resource_proto  = EXCLUDED.resource_proto,
			res_version     = fhir_resource.res_version + 1,
			last_updated    = NOW(),
			idempotency_key = EXCLUDED.idempotency_key,
			is_deleted      = FALSE
		RETURNING res_version, last_updated
	`, input.TenantID, input.ResType, input.ResID, input.ResourceProto, input.IdempotencyKey).Scan(&newVersion, &lastUpdated)
	if err != nil {
		return nil, fmt.Errorf("upsert resource: %w", err)
	}

	// 2. Append to version history table
	_, err = tx.ExecContext(ctx, `
		INSERT INTO fhir_resource_history (tenant_id, res_type, res_id, res_version, last_updated, resource_proto, is_deleted)
		VALUES ($1, $2, $3, $4, $5, $6, FALSE)
		ON CONFLICT (tenant_id, res_type, res_id, res_version) DO UPDATE SET
			last_updated   = EXCLUDED.last_updated,
			resource_proto = EXCLUDED.resource_proto,
			is_deleted     = FALSE
	`, input.TenantID, input.ResType, input.ResID, newVersion, lastUpdated, input.ResourceProto)
	if err != nil {
		return nil, fmt.Errorf("insert history: %w", err)
	}

	// 3. Delete old search indexes
	if err := deleteSearchIndexes(ctx, tx, input.TenantID, input.ResType, input.ResID); err != nil {
		return nil, fmt.Errorf("delete indexes: %w", err)
	}

	// 4. Bulk insert new search indexes
	if input.SearchIndexes != nil {
		if err := insertSearchIndexes(ctx, tx, input.SearchIndexes); err != nil {
			return nil, fmt.Errorf("insert indexes: %w", err)
		}
	}

	return &ResourceRecord{
		TenantID:      input.TenantID,
		ResType:       input.ResType,
		ResID:         input.ResID,
		ResVersion:    newVersion,
		LastUpdated:   lastUpdated,
		ResourceProto: input.ResourceProto,
		IsDeleted:     false,
		Created:       created,
	}, nil
}

// ReadResource reads a single resource by (tenant_id, res_type, res_id).
// Returns the proto-encoded resource bytes, or sql.ErrNoRows if not found or deleted.
func (s *Store) ReadResource(ctx context.Context, tenantID, resType, resID string) ([]byte, error) {
	var proto []byte
	err := s.db.QueryRowContext(ctx, `
		SELECT resource_proto FROM fhir_resource
		WHERE tenant_id = $1 AND res_type = $2 AND res_id = $3 AND is_deleted = FALSE
	`, tenantID, resType, resID).Scan(&proto)
	if err != nil {
		return nil, err
	}
	return proto, nil
}

// ReadResourceWithMeta reads a single resource and its version metadata.
// Returns sql.ErrNoRows if the resource never existed, or ErrResourceDeleted
// (alongside the tombstone ResourceRecord) if the resource was soft-deleted.
func (s *Store) ReadResourceWithMeta(ctx context.Context, tenantID, resType, resID string) (*ResourceRecord, error) {
	rec := &ResourceRecord{
		TenantID: tenantID,
		ResType:  resType,
		ResID:    resID,
	}
	err := s.db.QueryRowContext(ctx, `
		SELECT resource_proto, res_version, last_updated, is_deleted
		FROM fhir_resource
		WHERE tenant_id = $1 AND res_type = $2 AND res_id = $3
	`, tenantID, resType, resID).Scan(&rec.ResourceProto, &rec.ResVersion, &rec.LastUpdated, &rec.IsDeleted)
	if err != nil {
		return nil, err
	}
	if rec.IsDeleted {
		return rec, ErrResourceDeleted
	}
	return rec, nil
}

// ReadResourceVersion reads a specific historical version of a resource (FHIR vread).
// Returns sql.ErrNoRows if the version does not exist, or ErrResourceDeleted if
// that version is a deletion tombstone.
func (s *Store) ReadResourceVersion(ctx context.Context, tenantID, resType, resID string, version int) (*ResourceRecord, error) {
	rec := &ResourceRecord{
		TenantID: tenantID,
		ResType:  resType,
		ResID:    resID,
	}
	err := s.db.QueryRowContext(ctx, `
		SELECT resource_proto, res_version, last_updated, is_deleted
		FROM fhir_resource_history
		WHERE tenant_id = $1 AND res_type = $2 AND res_id = $3 AND res_version = $4
	`, tenantID, resType, resID, version).Scan(&rec.ResourceProto, &rec.ResVersion, &rec.LastUpdated, &rec.IsDeleted)
	if errors.Is(err, sql.ErrNoRows) {
		// Fallback to fhir_resource if row was seeded directly without history table entry.
		err = s.db.QueryRowContext(ctx, `
			SELECT resource_proto, res_version, last_updated, is_deleted
			FROM fhir_resource
			WHERE tenant_id = $1 AND res_type = $2 AND res_id = $3 AND res_version = $4
		`, tenantID, resType, resID, version).Scan(&rec.ResourceProto, &rec.ResVersion, &rec.LastUpdated, &rec.IsDeleted)
	}
	if err != nil {
		return nil, err
	}
	if rec.IsDeleted {
		return rec, ErrResourceDeleted
	}
	return rec, nil
}

// ListResourceHistory returns the version history of a resource ordered by version descending.
func (s *Store) ListResourceHistory(ctx context.Context, tenantID, resType, resID string, limit, offset int) ([]ResourceRecord, int, error) {
	if limit <= 0 {
		limit = 100
	}
	if offset < 0 {
		offset = 0
	}

	var total int
	if err := s.db.QueryRowContext(ctx, `
		SELECT COUNT(*) FROM fhir_resource_history
		WHERE tenant_id = $1 AND res_type = $2 AND res_id = $3
	`, tenantID, resType, resID).Scan(&total); err != nil {
		return nil, 0, fmt.Errorf("count resource history: %w", err)
	}

	rows, err := s.db.QueryContext(ctx, `
		SELECT resource_proto, res_version, last_updated, is_deleted
		FROM fhir_resource_history
		WHERE tenant_id = $1 AND res_type = $2 AND res_id = $3
		ORDER BY res_version DESC
		LIMIT $4 OFFSET $5
	`, tenantID, resType, resID, limit, offset)
	if err != nil {
		return nil, 0, fmt.Errorf("query resource history: %w", err)
	}
	defer rows.Close()

	var records []ResourceRecord
	for rows.Next() {
		rec := ResourceRecord{
			TenantID: tenantID,
			ResType:  resType,
			ResID:    resID,
		}
		if err := rows.Scan(&rec.ResourceProto, &rec.ResVersion, &rec.LastUpdated, &rec.IsDeleted); err != nil {
			return nil, 0, fmt.Errorf("scan resource history: %w", err)
		}
		records = append(records, rec)
	}
	if err := rows.Err(); err != nil {
		return nil, 0, err
	}
	return records, total, nil
}

// DeleteResource marks a resource as deleted (soft delete) and removes its search indexes.
func (s *Store) DeleteResource(ctx context.Context, tenantID, resType, resID string) error {
	_, err := s.DeleteResourceWithMeta(ctx, tenantID, resType, resID)
	if errors.Is(err, sql.ErrNoRows) {
		return nil
	}
	return err
}

// DeleteResourceWithMeta marks a resource as deleted, increments its version,
// records a deletion tombstone in fhir_resource_history, and clears search indexes.
// Returns sql.ErrNoRows if the resource does not exist.
func (s *Store) DeleteResourceWithMeta(ctx context.Context, tenantID, resType, resID string) (*ResourceRecord, error) {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return nil, fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback() //nolint:errcheck

	var curVersion int
	var curUpdated time.Time
	var curDeleted bool
	err = tx.QueryRowContext(ctx, `
		SELECT res_version, last_updated, is_deleted
		FROM fhir_resource
		WHERE tenant_id = $1 AND res_type = $2 AND res_id = $3
		FOR UPDATE
	`, tenantID, resType, resID).Scan(&curVersion, &curUpdated, &curDeleted)
	if err != nil {
		return nil, err
	}

	if curDeleted {
		return &ResourceRecord{
			TenantID:    tenantID,
			ResType:     resType,
			ResID:       resID,
			ResVersion:  curVersion,
			LastUpdated: curUpdated,
			IsDeleted:   true,
		}, nil
	}

	var newVersion int
	var lastUpdated time.Time
	err = tx.QueryRowContext(ctx, `
		UPDATE fhir_resource
		SET is_deleted = TRUE, res_version = res_version + 1, last_updated = NOW()
		WHERE tenant_id = $1 AND res_type = $2 AND res_id = $3
		RETURNING res_version, last_updated
	`, tenantID, resType, resID).Scan(&newVersion, &lastUpdated)
	if err != nil {
		return nil, fmt.Errorf("soft delete: %w", err)
	}

	_, err = tx.ExecContext(ctx, `
		INSERT INTO fhir_resource_history (tenant_id, res_type, res_id, res_version, last_updated, resource_proto, is_deleted)
		VALUES ($1, $2, $3, $4, $5, NULL, TRUE)
		ON CONFLICT (tenant_id, res_type, res_id, res_version) DO UPDATE SET
			last_updated   = EXCLUDED.last_updated,
			resource_proto = NULL,
			is_deleted     = TRUE
	`, tenantID, resType, resID, newVersion, lastUpdated)
	if err != nil {
		return nil, fmt.Errorf("insert delete history: %w", err)
	}

	if err := deleteSearchIndexes(ctx, tx, tenantID, resType, resID); err != nil {
		return nil, fmt.Errorf("delete indexes: %w", err)
	}

	if err := tx.Commit(); err != nil {
		return nil, err
	}

	return &ResourceRecord{
		TenantID:    tenantID,
		ResType:     resType,
		ResID:       resID,
		ResVersion:  newVersion,
		LastUpdated: lastUpdated,
		IsDeleted:   true,
	}, nil
}

// deleteSearchIndexes removes all search index rows for a resource.
func deleteSearchIndexes(ctx context.Context, tx *sql.Tx, tenantID, resType, resID string) error {
	tables := []string{
		"spidx_string",
		"spidx_token",
		"spidx_date",
		"spidx_reference",
		"spidx_quantity",
		"spidx_uri",
	}

	for _, table := range tables {
		_, err := tx.ExecContext(ctx, fmt.Sprintf(
			"DELETE FROM %s WHERE tenant_id = $1 AND res_type = $2 AND res_id = $3", table,
		), tenantID, resType, resID)
		if err != nil {
			return fmt.Errorf("delete from %s: %w", table, err)
		}
	}
	return nil
}

// insertSearchIndexes bulk inserts all search index rows for a resource.
func insertSearchIndexes(ctx context.Context, tx *sql.Tx, idx *SearchIndexes) error {
	if len(idx.Strings) > 0 {
		if err := bulkInsertStrings(ctx, tx, idx.Strings); err != nil {
			return err
		}
	}
	if len(idx.Tokens) > 0 {
		if err := bulkInsertTokens(ctx, tx, idx.Tokens); err != nil {
			return err
		}
	}
	if len(idx.Dates) > 0 {
		if err := bulkInsertDates(ctx, tx, idx.Dates); err != nil {
			return err
		}
	}
	if len(idx.References) > 0 {
		if err := bulkInsertReferences(ctx, tx, idx.References); err != nil {
			return err
		}
	}
	if len(idx.Quantities) > 0 {
		if err := bulkInsertQuantities(ctx, tx, idx.Quantities); err != nil {
			return err
		}
	}
	if len(idx.URIs) > 0 {
		if err := bulkInsertURIs(ctx, tx, idx.URIs); err != nil {
			return err
		}
	}
	return nil
}

// bulkInsertStrings inserts string search index rows using a multi-row VALUES clause.
func bulkInsertStrings(ctx context.Context, tx *sql.Tx, rows []SpidxString) error {
	var b strings.Builder
	args := make([]any, 0, len(rows)*5)
	b.WriteString("INSERT INTO spidx_string (tenant_id, res_type, res_id, sp_name, sp_value) VALUES ")
	for i, r := range rows {
		if i > 0 {
			b.WriteString(", ")
		}
		n := i * 5
		fmt.Fprintf(&b, "($%d, $%d, $%d, $%d, $%d)", n+1, n+2, n+3, n+4, n+5)
		args = append(args, r.TenantID, r.ResType, r.ResID, r.SpName, r.SpValue)
	}
	b.WriteString(" ON CONFLICT DO NOTHING")
	_, err := tx.ExecContext(ctx, b.String(), args...)
	return err
}

// bulkInsertTokens inserts token search index rows.
func bulkInsertTokens(ctx context.Context, tx *sql.Tx, rows []SpidxToken) error {
	var b strings.Builder
	args := make([]any, 0, len(rows)*6)
	b.WriteString("INSERT INTO spidx_token (tenant_id, res_type, res_id, sp_name, sp_system, sp_value) VALUES ")
	for i, r := range rows {
		if i > 0 {
			b.WriteString(", ")
		}
		n := i * 6
		fmt.Fprintf(&b, "($%d, $%d, $%d, $%d, $%d, $%d)", n+1, n+2, n+3, n+4, n+5, n+6)
		args = append(args, r.TenantID, r.ResType, r.ResID, r.SpName, r.SpSystem, r.SpValue)
	}
	b.WriteString(" ON CONFLICT DO NOTHING")
	_, err := tx.ExecContext(ctx, b.String(), args...)
	return err
}

// bulkInsertDates inserts date search index rows.
func bulkInsertDates(ctx context.Context, tx *sql.Tx, rows []SpidxDate) error {
	var b strings.Builder
	args := make([]any, 0, len(rows)*6)
	b.WriteString("INSERT INTO spidx_date (tenant_id, res_type, res_id, sp_name, sp_low, sp_high) VALUES ")
	for i, r := range rows {
		if i > 0 {
			b.WriteString(", ")
		}
		n := i * 6
		fmt.Fprintf(&b, "($%d, $%d, $%d, $%d, $%d, $%d)", n+1, n+2, n+3, n+4, n+5, n+6)
		args = append(args, r.TenantID, r.ResType, r.ResID, r.SpName, r.SpLow, r.SpHigh)
	}
	b.WriteString(" ON CONFLICT DO NOTHING")
	_, err := tx.ExecContext(ctx, b.String(), args...)
	return err
}

// bulkInsertReferences inserts reference search index rows.
func bulkInsertReferences(ctx context.Context, tx *sql.Tx, rows []SpidxReference) error {
	var b strings.Builder
	args := make([]any, 0, len(rows)*6)
	b.WriteString("INSERT INTO spidx_reference (tenant_id, res_type, res_id, sp_name, target_type, target_id) VALUES ")
	for i, r := range rows {
		if i > 0 {
			b.WriteString(", ")
		}
		n := i * 6
		fmt.Fprintf(&b, "($%d, $%d, $%d, $%d, $%d, $%d)", n+1, n+2, n+3, n+4, n+5, n+6)
		args = append(args, r.TenantID, r.ResType, r.ResID, r.SpName, r.TargetType, r.TargetID)
	}
	b.WriteString(" ON CONFLICT DO NOTHING")
	_, err := tx.ExecContext(ctx, b.String(), args...)
	return err
}

// bulkInsertQuantities inserts quantity search index rows.
func bulkInsertQuantities(ctx context.Context, tx *sql.Tx, rows []SpidxQuantity) error {
	var b strings.Builder
	args := make([]any, 0, len(rows)*7)
	b.WriteString("INSERT INTO spidx_quantity (tenant_id, res_type, res_id, sp_name, sp_system, sp_code, sp_value) VALUES ")
	for i, r := range rows {
		if i > 0 {
			b.WriteString(", ")
		}
		n := i * 7
		fmt.Fprintf(&b, "($%d, $%d, $%d, $%d, $%d, $%d, $%d)", n+1, n+2, n+3, n+4, n+5, n+6, n+7)
		args = append(args, r.TenantID, r.ResType, r.ResID, r.SpName, r.SpSystem, r.SpCode, r.SpValue)
	}
	b.WriteString(" ON CONFLICT DO NOTHING")
	_, err := tx.ExecContext(ctx, b.String(), args...)
	return err
}

// bulkInsertURIs inserts URI search index rows.
func bulkInsertURIs(ctx context.Context, tx *sql.Tx, rows []SpidxURI) error {
	var b strings.Builder
	args := make([]any, 0, len(rows)*5)
	b.WriteString("INSERT INTO spidx_uri (tenant_id, res_type, res_id, sp_name, sp_value) VALUES ")
	for i, r := range rows {
		if i > 0 {
			b.WriteString(", ")
		}
		n := i * 5
		fmt.Fprintf(&b, "($%d, $%d, $%d, $%d, $%d)", n+1, n+2, n+3, n+4, n+5)
		args = append(args, r.TenantID, r.ResType, r.ResID, r.SpName, r.SpValue)
	}
	b.WriteString(" ON CONFLICT DO NOTHING")
	_, err := tx.ExecContext(ctx, b.String(), args...)
	return err
}
