// Package postgres implements the Flint FHIR resource store using PostgreSQL.
//
// It stores FHIR resources as proto-encoded blobs with HAPI-style search index
// tables (spidx_*) for efficient FHIR search operations. Resources are written
// in a single transaction: upsert blob + delete old indexes + bulk insert new indexes.
package postgres

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	genpostgres "github.com/flint-fhir/flint/gen/go/store/postgres"
)

// SearchIndexes holds all extracted search index rows for a resource.
// This type is generated by proto2type (postgres_mode=search_index).
type SearchIndexes = genpostgres.SearchIndexes

type SpidxString = genpostgres.SpidxString
type SpidxToken = genpostgres.SpidxToken
type SpidxDate = genpostgres.SpidxDate
type SpidxReference = genpostgres.SpidxReference
type SpidxQuantity = genpostgres.SpidxQuantity
type SpidxURI = genpostgres.SpidxURI

// IndexExtractorFunc extracts search indexes from a proto-encoded resource.
type IndexExtractorFunc func(tenantID string, resID string, protoBytes []byte) (*SearchIndexes, error)

// ResourceInput is the input to write a single FHIR resource.
type ResourceInput struct {
	TenantID       string
	ResType        string
	ResID          string
	ResourceProto  []byte         // proto-encoded FHIR resource
	SearchIndexes  *SearchIndexes // extracted search index rows
	IdempotencyKey string         // Bundle ID for dedup
}

// Store provides FHIR resource storage operations on Postgres.
type Store struct {
	db *sql.DB
}

// New creates a new Postgres FHIR resource store.
func New(db *sql.DB) *Store {
	return &Store{db: db}
}

// WriteResource writes a single resource in a single transaction:
// 1. Upsert the resource blob
// 2. Delete old search indexes for this resource
// 3. Bulk insert new search indexes
//
// This is idempotent: re-processing the same resource produces the same state.
func (s *Store) WriteResource(ctx context.Context, input ResourceInput) error {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback() //nolint:errcheck

	// 1. Upsert resource blob
	_, err = tx.ExecContext(ctx, `
		INSERT INTO fhir_resource (tenant_id, res_type, res_id, resource_proto, idempotency_key, last_updated)
		VALUES ($1, $2, $3, $4, $5, NOW())
		ON CONFLICT (tenant_id, res_type, res_id) DO UPDATE SET
			resource_proto  = EXCLUDED.resource_proto,
			res_version     = fhir_resource.res_version + 1,
			last_updated    = NOW(),
			idempotency_key = EXCLUDED.idempotency_key,
			is_deleted      = FALSE
	`, input.TenantID, input.ResType, input.ResID, input.ResourceProto, input.IdempotencyKey)
	if err != nil {
		return fmt.Errorf("upsert resource: %w", err)
	}

	// 2. Delete old search indexes
	if err := deleteSearchIndexes(ctx, tx, input.TenantID, input.ResType, input.ResID); err != nil {
		return fmt.Errorf("delete indexes: %w", err)
	}

	// 3. Bulk insert new search indexes
	if input.SearchIndexes != nil {
		if err := insertSearchIndexes(ctx, tx, input.SearchIndexes); err != nil {
			return fmt.Errorf("insert indexes: %w", err)
		}
	}

	return tx.Commit()
}

// WriteBatch writes multiple resources in a single transaction.
// This is the hot path for FHIR Bundle ingestion (R8: batch per Bundle).
func (s *Store) WriteBatch(ctx context.Context, inputs []ResourceInput) error {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback() //nolint:errcheck

	for _, input := range inputs {
		// Upsert resource blob
		_, err = tx.ExecContext(ctx, `
			INSERT INTO fhir_resource (tenant_id, res_type, res_id, resource_proto, idempotency_key, last_updated)
			VALUES ($1, $2, $3, $4, $5, NOW())
			ON CONFLICT (tenant_id, res_type, res_id) DO UPDATE SET
				resource_proto  = EXCLUDED.resource_proto,
				res_version     = fhir_resource.res_version + 1,
				last_updated    = NOW(),
				idempotency_key = EXCLUDED.idempotency_key,
				is_deleted      = FALSE
		`, input.TenantID, input.ResType, input.ResID, input.ResourceProto, input.IdempotencyKey)
		if err != nil {
			return fmt.Errorf("upsert resource %s/%s: %w", input.ResType, input.ResID, err)
		}

		// Delete old indexes
		if err := deleteSearchIndexes(ctx, tx, input.TenantID, input.ResType, input.ResID); err != nil {
			return fmt.Errorf("delete indexes %s/%s: %w", input.ResType, input.ResID, err)
		}

		// Insert new indexes
		if input.SearchIndexes != nil {
			if err := insertSearchIndexes(ctx, tx, input.SearchIndexes); err != nil {
				return fmt.Errorf("insert indexes %s/%s: %w", input.ResType, input.ResID, err)
			}
		}
	}

	return tx.Commit()
}

// ReadResource reads a single resource by (tenant_id, res_type, res_id).
// Returns the proto-encoded resource bytes, or sql.ErrNoRows if not found.
func (s *Store) ReadResource(ctx context.Context, tenantID, resType, resID string) ([]byte, error) {
	var proto []byte
	err := s.db.QueryRowContext(ctx, `
		SELECT resource_proto FROM fhir_resource
		WHERE tenant_id = $1 AND res_type = $2 AND res_id = $3 AND is_deleted = FALSE
	`, tenantID, resType, resID).Scan(&proto)
	if err != nil {
		return nil, err
	}
	return proto, nil
}

// DeleteResource marks a resource as deleted (soft delete).
func (s *Store) DeleteResource(ctx context.Context, tenantID, resType, resID string) error {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback() //nolint:errcheck

	_, err = tx.ExecContext(ctx, `
		UPDATE fhir_resource SET is_deleted = TRUE, last_updated = NOW()
		WHERE tenant_id = $1 AND res_type = $2 AND res_id = $3
	`, tenantID, resType, resID)
	if err != nil {
		return fmt.Errorf("soft delete: %w", err)
	}

	if err := deleteSearchIndexes(ctx, tx, tenantID, resType, resID); err != nil {
		return fmt.Errorf("delete indexes: %w", err)
	}

	return tx.Commit()
}

// deleteSearchIndexes removes all search index rows for a resource.
func deleteSearchIndexes(ctx context.Context, tx *sql.Tx, tenantID, resType, resID string) error {
	tables := []string{
		"spidx_string",
		"spidx_token",
		"spidx_date",
		"spidx_reference",
		"spidx_quantity",
		"spidx_uri",
	}

	for _, table := range tables {
		_, err := tx.ExecContext(ctx, fmt.Sprintf(
			"DELETE FROM %s WHERE tenant_id = $1 AND res_type = $2 AND res_id = $3", table,
		), tenantID, resType, resID)
		if err != nil {
			return fmt.Errorf("delete from %s: %w", table, err)
		}
	}
	return nil
}

// insertSearchIndexes bulk inserts all search index rows for a resource.
func insertSearchIndexes(ctx context.Context, tx *sql.Tx, idx *SearchIndexes) error {
	if len(idx.Strings) > 0 {
		if err := bulkInsertStrings(ctx, tx, idx.Strings); err != nil {
			return err
		}
	}
	if len(idx.Tokens) > 0 {
		if err := bulkInsertTokens(ctx, tx, idx.Tokens); err != nil {
			return err
		}
	}
	if len(idx.Dates) > 0 {
		if err := bulkInsertDates(ctx, tx, idx.Dates); err != nil {
			return err
		}
	}
	if len(idx.References) > 0 {
		if err := bulkInsertReferences(ctx, tx, idx.References); err != nil {
			return err
		}
	}
	if len(idx.Quantities) > 0 {
		if err := bulkInsertQuantities(ctx, tx, idx.Quantities); err != nil {
			return err
		}
	}
	if len(idx.URIs) > 0 {
		if err := bulkInsertURIs(ctx, tx, idx.URIs); err != nil {
			return err
		}
	}
	return nil
}

// bulkInsertStrings inserts string search index rows using a multi-row VALUES clause.
func bulkInsertStrings(ctx context.Context, tx *sql.Tx, rows []SpidxString) error {
	var b strings.Builder
	args := make([]any, 0, len(rows)*5)
	b.WriteString("INSERT INTO spidx_string (tenant_id, res_type, res_id, sp_name, sp_value) VALUES ")
	for i, r := range rows {
		if i > 0 {
			b.WriteString(", ")
		}
		n := i * 5
		fmt.Fprintf(&b, "($%d, $%d, $%d, $%d, $%d)", n+1, n+2, n+3, n+4, n+5)
		args = append(args, r.TenantID, r.ResType, r.ResID, r.SpName, r.SpValue)
	}
	b.WriteString(" ON CONFLICT DO NOTHING")
	_, err := tx.ExecContext(ctx, b.String(), args...)
	return err
}

// bulkInsertTokens inserts token search index rows.
func bulkInsertTokens(ctx context.Context, tx *sql.Tx, rows []SpidxToken) error {
	var b strings.Builder
	args := make([]any, 0, len(rows)*6)
	b.WriteString("INSERT INTO spidx_token (tenant_id, res_type, res_id, sp_name, sp_system, sp_value) VALUES ")
	for i, r := range rows {
		if i > 0 {
			b.WriteString(", ")
		}
		n := i * 6
		fmt.Fprintf(&b, "($%d, $%d, $%d, $%d, $%d, $%d)", n+1, n+2, n+3, n+4, n+5, n+6)
		args = append(args, r.TenantID, r.ResType, r.ResID, r.SpName, r.SpSystem, r.SpValue)
	}
	b.WriteString(" ON CONFLICT DO NOTHING")
	_, err := tx.ExecContext(ctx, b.String(), args...)
	return err
}

// bulkInsertDates inserts date search index rows.
func bulkInsertDates(ctx context.Context, tx *sql.Tx, rows []SpidxDate) error {
	var b strings.Builder
	args := make([]any, 0, len(rows)*6)
	b.WriteString("INSERT INTO spidx_date (tenant_id, res_type, res_id, sp_name, sp_low, sp_high) VALUES ")
	for i, r := range rows {
		if i > 0 {
			b.WriteString(", ")
		}
		n := i * 6
		fmt.Fprintf(&b, "($%d, $%d, $%d, $%d, $%d, $%d)", n+1, n+2, n+3, n+4, n+5, n+6)
		args = append(args, r.TenantID, r.ResType, r.ResID, r.SpName, r.SpLow, r.SpHigh)
	}
	b.WriteString(" ON CONFLICT DO NOTHING")
	_, err := tx.ExecContext(ctx, b.String(), args...)
	return err
}

// bulkInsertReferences inserts reference search index rows.
func bulkInsertReferences(ctx context.Context, tx *sql.Tx, rows []SpidxReference) error {
	var b strings.Builder
	args := make([]any, 0, len(rows)*6)
	b.WriteString("INSERT INTO spidx_reference (tenant_id, res_type, res_id, sp_name, target_type, target_id) VALUES ")
	for i, r := range rows {
		if i > 0 {
			b.WriteString(", ")
		}
		n := i * 6
		fmt.Fprintf(&b, "($%d, $%d, $%d, $%d, $%d, $%d)", n+1, n+2, n+3, n+4, n+5, n+6)
		args = append(args, r.TenantID, r.ResType, r.ResID, r.SpName, r.TargetType, r.TargetID)
	}
	b.WriteString(" ON CONFLICT DO NOTHING")
	_, err := tx.ExecContext(ctx, b.String(), args...)
	return err
}

// bulkInsertQuantities inserts quantity search index rows.
func bulkInsertQuantities(ctx context.Context, tx *sql.Tx, rows []SpidxQuantity) error {
	var b strings.Builder
	args := make([]any, 0, len(rows)*7)
	b.WriteString("INSERT INTO spidx_quantity (tenant_id, res_type, res_id, sp_name, sp_system, sp_code, sp_value) VALUES ")
	for i, r := range rows {
		if i > 0 {
			b.WriteString(", ")
		}
		n := i * 7
		fmt.Fprintf(&b, "($%d, $%d, $%d, $%d, $%d, $%d, $%d)", n+1, n+2, n+3, n+4, n+5, n+6, n+7)
		args = append(args, r.TenantID, r.ResType, r.ResID, r.SpName, r.SpSystem, r.SpCode, r.SpValue)
	}
	b.WriteString(" ON CONFLICT DO NOTHING")
	_, err := tx.ExecContext(ctx, b.String(), args...)
	return err
}

// bulkInsertURIs inserts URI search index rows.
func bulkInsertURIs(ctx context.Context, tx *sql.Tx, rows []SpidxURI) error {
	var b strings.Builder
	args := make([]any, 0, len(rows)*5)
	b.WriteString("INSERT INTO spidx_uri (tenant_id, res_type, res_id, sp_name, sp_value) VALUES ")
	for i, r := range rows {
		if i > 0 {
			b.WriteString(", ")
		}
		n := i * 5
		fmt.Fprintf(&b, "($%d, $%d, $%d, $%d, $%d)", n+1, n+2, n+3, n+4, n+5)
		args = append(args, r.TenantID, r.ResType, r.ResID, r.SpName, r.SpValue)
	}
	b.WriteString(" ON CONFLICT DO NOTHING")
	_, err := tx.ExecContext(ctx, b.String(), args...)
	return err
}
